version: 2.1
orbs:
  node: circleci/maven@1.4.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.8
    steps:
      - checkout
      - run:
          name: Build Maven Project
          command: mvn install


  test:
    docker:
      - image: cimg/openjdk:17.0.8
    steps:
      - checkout
      - run:
          name: Test Maven Project 
          command: mvn test

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: alf1650/software-4-projectwork
          tag: <<pipeline.git.tag>>
      - docker/push:
          image: alf1650/software-4-projectwork
          tag: <<pipeline.git.tag>>

  scan:
    docker: 
      - image: cimg/openjdk:17.0.8
    environment:
      IMAGE_NAME: alf1650/software-4-projectwork
    steps: 
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan: 
          docker-image-name: $IMAGE_NAME
          severity-threshold: low  # Adjust the severity threshold as needed
          fail-on-issues: false

  deploy:
    docker:
      - image: cimg/openjdk:17.0.8
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - heroku/install
      - checkout
      - run:
          name: Set FORCE_SSL to false on Heroku
          command: |
            heroku config:set FORCE_SSL=false -a alf1650
      
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku container:push web -a alf1650
            heroku container:release web -a alf1650

workflows:
  ci_flow:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - test:
          requires:
            - build
          filters:
            branches:
              only: develop
      - build-and-push:
          requires:
            - test
          filters:
            branches:
              only: develop
      - scan:
          requires:
            - build

  cicd_flow:
    jobs:
      - build:
          filters:
            branches:
              only: release
      - test:
          requires:
            - build
          filters:
            branches:
              only: release
      - build-and-push:
          requires:
            - test
          filters:
            branches:
              only: release
      - scan:
          requires:
            - build
      - deploy:
          requires:
            - build-and-push

